### ISSUE TITLE
Error: TOR: Connection already established

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1103]
decktop v 0.15.4

<img width="390" alt="image (3)" src="https://user-images.githubusercontent.com/68909168/207097160-63567cc4-a335-4e24-beb8-357ea567cb87.png">

C:\Users\WinFish\Desktop\Quiet.lnk
PS C:\Users\WinFish> C:\Users\WinFish\AppData\Local\Programs\quiet\Quiet.exe
PS C:\Users\WinFish>
Read extra envs: { TEST_MODE: 'true' }
Checking for update
Update for version 0.14.5-alpha.0 is not available (latest version: 0.14.5-alpha.0, downgrade is disallowed).
connectionsManager
(node:5588) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\node_modules\@quiet\state-manager\node_modules\factory-girl\package.json' of './src/index'. Please either fix that or report it to the module author
(Use `Quiet --trace-deprecation ...` to show where the warning was created)
Error: TOR: Connection already established
    at C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\torManager\TorControl.js:29:28
    at new Promise (<anonymous>)
    at TorControl.<anonymous> (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\torManager\TorControl.js:27:26)
    at Generator.next (<anonymous>)
    at C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\torManager\TorControl.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\torManager\TorControl.js:4:12)
    at TorControl.connect (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\torManager\TorControl.js:26:16)
    at TorControl.<anonymous> (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\torManager\TorControl.js:64:24)
    at Generator.next (<anonymous>)
C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\libp2p\connectionsManager.js:407
            throw new Error();
            ^
Error
    at process.<anonymous> (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\lib\libp2p\connectionsManager.js:407:19)
    at process.emit (node:events:526:28)
    at process.processEmit [as emit] (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\@quiet\backend\node_modules\signal-exit\index.js:197:34)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:97:32)

**Comment by kingalg** [comment]
v 0.16.0 - still bugged

We don't have specific steps to recreate but it happens mostly when opening or closing the app.

**Comment by holmesworcester** [comment]
I see this specifically when the app opens after an update. So I think it's something about how the update shuts down and restarts the app that is creating a problem.

I believe the same thing is happening on mobile but without the error message. On first run after update the app crashes (user returns to home screen) and works fine when you run it again.
