### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by pdurbin** [TryQuiet/quiet#1127]
This happened when I launched Quiet. Version 0.15.0.

<img width="532" alt="Screen Shot 2022-12-15 at 6 30 09 AM" src="https://user-images.githubusercontent.com/21006/207848642-f8b0be17-9157-4dff-b9f7-27da045a71ca.png">

<img width="912" alt="Screen Shot 2022-12-15 at 6 30 26 AM" src="https://user-images.githubusercontent.com/21006/207848628-e8a6852a-3be1-4466-b30c-4b8e05c7f1b5.png">

<img width="396" alt="Screen Shot 2022-12-15 at 6 30 55 AM" src="https://user-images.githubusercontent.com/21006/207848624-a5a5703d-1985-4e35-accc-ce3a40562ce6.png">

When I quit the app, I saw another error:

<img width="532" alt="Screen Shot 2022-12-15 at 6 34 13 AM" src="https://user-images.githubusercontent.com/21006/207849260-989e7c98-4363-48ce-909a-14d9bce66bbc.png">

**Comment by pdurbin** [comment]
I simply re-launched Quiet and it's working now. Closing.

<img width="912" alt="Screen Shot 2022-12-15 at 6 37 56 AM" src="https://user-images.githubusercontent.com/21006/207849947-1803b134-39bc-4d02-ae0c-f89678d38d0f.png">

**Comment by pdurbin** [comment]
This time on 0.16.0:

<img width="532" alt="Screen Shot 2022-12-20 at 8 49 16 PM" src="https://user-images.githubusercontent.com/21006/208801527-7a068fbb-1fda-47fe-8e33-03e7dddd559c.png">

**Comment by holmesworcester** [comment]
I've had two reports of this happening on **community creation**.

![image](https://user-images.githubusercontent.com/213678/211580121-9b809b72-dcb4-41bb-8b7a-3afeda74629b.png)

**Comment by holmesworcester** [comment]
@kingalg try creating communities a lot on Mac (M1 and non M1)

**Comment by kingalg** [comment]
v 0.16.0-alpha
Chromebook

It's general error and it may not be the same issue but for now let's gather all the information that we have. if it's connected - great, we at least have some logs, if it's not we will split this issue upon receiving more info. 

My steps (but I can't really reproduce it, it was really random):
1. I've joined community with Chromebook and v 0.16.0-alpha
2. Everything was working as expected. History loaded, user could communicate with other users. No issue spotted. 
3. I've put Chromebook to sleep for 2 days without closing Quiet. 
4. I've opened Chromebook and Quiet with this error and logs was already there. 

<img width="611" alt="Screenshot 2023-01-12 at 13 42 10" src="https://user-images.githubusercontent.com/68909168/212069221-dfbf1ee6-7773-43b1-8b45-af36dfa3b857.png">

Update for version 0.16.0-alpha.0 is not available (latest version: 0.16.0-alpha.0, downgrade is disallowed).
Checking for update
Update for version 0.16.0-alpha.0 is not available (latest version: 0.16.0-alpha.0, downgrade is disallowed).
Checking for update
Error
    at new module.exports.TimeoutError (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/promise-timeout/index.js:44:16)
    at module.exports.timeout (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/promise-timeout/index.js:20:15)
    at /tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/mortice/lib/index.js:17:19
    at run (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/p-queue/dist/index.js:157:104)
    at PQueue._tryToStartAnother (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/p-queue/dist/index.js:105:17)
    at /tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/p-queue/dist/index.js:171:18
    at new Promise (<anonymous>)
    at PQueue.add (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/p-queue/dist/index.js:152:16)
    at createReleaseable (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/mortice/lib/index.js:17:9)
    at Object.readLock (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/mortice/lib/index.js:43:16)
/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/lib/libp2p/connectionsManager.js:407
            throw new Error();
            ^
Error
    at process.<anonymous> (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/lib/libp2p/connectionsManager.js:407:19)
    at process.emit (node:events:526:28)
    at process.processEmit [as emit] (/tmp/.mount_Quiet-POeio2/resources/app.asar/node_modules/@quiet/backend/node_modules/signal-exit/index.js:197:34)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at process.processTimers (node:internal/timers:502:7)

**Comment by kingalg** [comment]
I turned off Quiet in the state it was in previous post and below you can see new error and logs.

<img width="358" alt="Screenshot 2023-01-12 at 15 29 12" src="https://user-images.githubusercontent.com/68909168/212093196-44172835-c319-46c7-896e-37515d2996a9.png">

^CError: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)

**Comment by pdurbin** [comment]
I'm seeing similar errors (I think) when I try to launch Quiet on my work computer.

## just after launch
<img width="880" alt="Screen Shot 2023-01-31 at 4 08 39 PM" src="https://user-images.githubusercontent.com/21006/215883937-c550e1b6-e5ae-4104-8c02-9a71f0dfd6ff.png">

## Understand
<img width="880" alt="Screen Shot 2023-01-31 at 4 08 49 PM" src="https://user-images.githubusercontent.com/21006/215883939-aaf14281-1add-4140-aa1a-1b639d0a290a.png">

## Wait for a long time
<img width="880" alt="Screen Shot 2023-01-31 at 4 09 02 PM" src="https://user-images.githubusercontent.com/21006/215883932-48fb8313-1568-4521-97cc-239b211bc4ed.png">

## Keep waiting, let's show the version at least (0.19.6)
<img width="880" alt="Screen Shot 2023-01-31 at 4 09 14 PM" src="https://user-images.githubusercontent.com/21006/215883941-d976acbf-e531-4865-b00c-9fe713d212ff.png">

Not sure how to fix this.

**Comment by pdurbin** [comment]
@holmesworcester helped me uninstall the alpha version of Quiet I was on (see above). Then I installed the version from the website (0.16.0). All set, I think. Closing! Thanks!
