### ISSUE TITLE
Unable to use the Linux app after the latest upgrade 

### ISSUE THREAD

**Issue by 5mutawa** [TryQuiet/quiet#1365]
After upgrading to 1.1.1, the Linux app gets stuck at "Initializing Community" and throws the error,

 ![image](https://user-images.githubusercontent.com/7039768/227575355-7c427f30-795d-491c-8b9a-6ca08485a0f0.png)

Also,

```
Checking for update
Update for version 1.1.1 is not available (latest version: 1.1.1, downgrade is disallowed).
ModuleError: Database is not open
    at maybeError (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:48313:27)
    at ClassicLevel.put (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:47926:9)
    at LocalDB.put (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:247738:23)
    at ConnectionsManager.launchCommunity (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:243165:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataServer.<anonymous> (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:242875:17) {
  code: 'LEVEL_DATABASE_NOT_OPEN'
}
/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:243089
            throw new Error();
            ^

Error
    at process.<anonymous> (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:243089:19)
    at process.emit (node:events:513:28)
    at process.processEmit [as emit] (/tmp/.mount_Quiet-SrR86r/resources/app.asar/node_modules/backend-bundle/bundle.cjs:239587:34)
```

**Comment by 5mutawa** [comment]
Closing this issue as it seem to be fixed somehow.
