### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/quiet#1428]
Getting a javascript error on every startup. 

* possible causes: #1427 or quitting app while connecting to tor and restarting. 
* Tor was still running after I quit.
* Killing Tor and restarting gives same error.
* Was testing downloading a large file (I don't think this is it)

![Image](https://user-images.githubusercontent.com/213678/230726727-460b8182-55d9-45f5-bb64-7b908ceb5670.png)

```
hwilson@signal-only:~$ ./Quiet-1.2.0-alpha.24.AppImage 
Read extra envs: { TEST_MODE: 'true' }
Couldn't set default scheme handler Command failed: xdg-settings set default-url-scheme-handler quiet quiet.desktop
setAsDefaultProtocolClient false
electron main
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[1442:0408/102554.764073:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764220:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764281:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764320:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764354:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764383:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764428:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764460:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764497:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764534:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764566:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764596:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764629:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764667:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764740:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764804:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764842:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764919:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.764983:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765057:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765133:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765188:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765256:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765310:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765368:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765420:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765472:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765535:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765593:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765752:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765877:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765932:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.765982:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766040:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766240:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766318:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766385:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766456:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766533:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1442:0408/102554.766643:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
WARNING: Missing strong random number source
options {
  socketIOPort: '39217',
  appDataPath: '/home/hwilson/.config/Quiet',
  resourcesPath: '/tmp/.mount_Quiet-x8cqUg/resources',
  platform: 'desktop'
}
Checking for update
[1442:0408/102557.484011:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1442:0408/102557.648627:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Update for version 1.2.0-alpha.24 is not available (latest version: 1.2.0-alpha.24, downgrade is disallowed).
hwilson@signal-only:~$ DEBUG=backend* ./Quiet-1.2.0-alpha.24.AppImage 
SHELL=/bin/bash
QT_ACCESSIBILITY=1
ARGV0=./Quiet-1.2.0-alpha.24.AppImage
XDG_CONFIG_HOME=/home/hwilson/.config
DISPLAY_LOW_DENSITY=:1
XCURSOR_SIZE=38
PWD=/home/hwilson
LOGNAME=hwilson
QT_QPA_PLATFORMTHEME=gtk2
VM_IDENTIFIER=dc041f9c-e10d-4171-90f4-dbed3cd56c85
WAYLAND_DISPLAY_LOW_DENSITY=wayland-1
XCURSOR_SIZE_LOW_DENSITY=19
SOMMELIER_VERSION=0.20
HOME=/home/hwilson
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=X-Generic
WAYLAND_DISPLAY=wayland-0
INVOCATION_ID=8b47d8f717674dc6ab5fd971042ccd32
MANAGERPID=139
APPDIR=/tmp/.mount_Quiet-I2kkug
SOMMELIER_DRM_DEVICE=/dev/dri/renderD128
TERM=xterm-256color
USER=hwilson
NCURSES_NO_UTF8_ACS=1
OWD=/home/hwilson
SOMMELIER_GLAMOR=1
DISPLAY=:0
SHLVL=2
APPIMAGE=/home/hwilson/Quiet-1.2.0-alpha.24.AppImage
XDG_RUNTIME_DIR=/run/user/1000
QT_AUTO_SCREEN_SCALE_FACTOR=1
JOURNAL_STREAM=7:21353
XCURSOR_THEME=Adwaita
XDG_DATA_DIRS=/home/hwilson/.local/share:/home/hwilson/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
BROWSER=/usr/bin/garcon-url-handler
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
LD_ARGV0_REL=../bin/vshd
DEBUG=backend*
_=/usr/bin/env
+ THIS=/tmp/.mount_Quiet-I2kkug/AppRun
+ args=("$@")
+ NUMBER_OF_ARGS=0
+ '[' -z /tmp/.mount_Quiet-I2kkug ']'
+ export PATH=/tmp/.mount_Quiet-I2kkug:/tmp/.mount_Quiet-I2kkug/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+ PATH=/tmp/.mount_Quiet-I2kkug:/tmp/.mount_Quiet-I2kkug/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
+ export XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/home/hwilson/.local/share:/home/hwilson/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
+ XDG_DATA_DIRS=./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/home/hwilson/.local/share:/home/hwilson/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
+ export LD_LIBRARY_PATH=/tmp/.mount_Quiet-I2kkug/usr/lib:
+ LD_LIBRARY_PATH=/tmp/.mount_Quiet-I2kkug/usr/lib:
+ export XDG_DATA_DIRS=/tmp/.mount_Quiet-I2kkug/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/home/hwilson/.local/share:/home/hwilson/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ XDG_DATA_DIRS=/tmp/.mount_Quiet-I2kkug/usr/share/:./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:/home/hwilson/.local/share:/home/hwilson/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/usr/share/gnome/:/usr/local/share/:/usr/share/
+ export GSETTINGS_SCHEMA_DIR=/tmp/.mount_Quiet-I2kkug/usr/share/glib-2.0/schemas:
+ GSETTINGS_SCHEMA_DIR=/tmp/.mount_Quiet-I2kkug/usr/share/glib-2.0/schemas:
+ export LD_PRELOAD=/tmp/.mount_Quiet-I2kkug/usr/lib/libssl.so
+ LD_PRELOAD=/tmp/.mount_Quiet-I2kkug/usr/lib/libssl.so
+ BIN=/tmp/.mount_Quiet-I2kkug/quiet
+ '[' -z '' ']'
+ trap atexit EXIT
+ isEulaAccepted=1
+ '[' -z /home/hwilson/Quiet-1.2.0-alpha.24.AppImage ']'
+ atexit
+ '[' 1 == 1 ']'
+ '[' 0 -eq 0 ']'
+ exec /tmp/.mount_Quiet-I2kkug/quiet
Read extra envs: { TEST_MODE: 'true' }
Couldn't set default scheme handler Command failed: xdg-settings set default-url-scheme-handler quiet quiet.desktop
setAsDefaultProtocolClient false
electron main
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[1866:0408/102609.786996:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.787315:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.787477:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.787637:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.787698:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.787800:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.787882:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788015:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788122:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788250:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788349:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788451:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788551:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.788655:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.790961:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.791311:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.791452:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.791663:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.791838:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.792134:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.792387:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.792603:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.792775:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.792971:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.793168:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.793363:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.793597:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.793863:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.794151:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.794374:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.794616:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.795054:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.795373:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.795945:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.796599:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.801034:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.801380:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.801561:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.801692:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
[1866:0408/102609.801938:ERROR:gbm_wrapper.cc(255)] Failed to export buffer to dma_buf: No such file or directory (2)
WARNING: Missing strong random number source
options {
  socketIOPort: '45147',
  appDataPath: '/home/hwilson/.config/Quiet',
  resourcesPath: '/tmp/.mount_Quiet-I2kkug/resources',
  platform: 'desktop'
}
  backend:conn Creating https proxy agent: 38897 +0ms
  backend:socket Data server running on port 45147 +0ms
[1866:0408/102611.933364:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[1866:0408/102611.939357:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[1866:0408/102611.955136:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
  backend:tor Initializing tor... +0ms
  backend:tor Trying to spawn tor for the 0 time... +149ms
  backend:tor Apr 08 10:26:12.410 [notice] Tor 0.4.7.13 (git-7c1601fb6edd780f) running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1h, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
  backend:tor Apr 08 10:26:12.410 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
  backend:tor Apr 08 10:26:12.410 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
  backend:tor  +31ms
  backend:tor Apr 08 10:26:12.414 [notice] Opening Socks listener on 127.0.0.1:46271
  backend:tor Apr 08 10:26:12.414 [notice] Opened Socks listener connection (ready) on 127.0.0.1:46271
  backend:tor Apr 08 10:26:12.414 [notice] Opening HTTP tunnel listener on 127.0.0.1:38897
  backend:tor Apr 08 10:26:12.414 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:38897
  backend:tor Apr 08 10:26:12.414 [notice] Opening Control listener on 127.0.0.1:34421
  backend:tor Apr 08 10:26:12.414 [notice] Opened Control listener connection (ready) on 127.0.0.1:34421
  backend:tor  +9ms
  backend:tor Apr 08 10:26:12.000 [notice] Bootstrapped 0% (starting): Starting
  backend:tor  +6ms
  backend:tor Apr 08 10:26:12.000 [notice] Starting with guard context "default"
  backend:tor  +244ms
Checking for update
Update for version 1.2.0-alpha.24 is not available (latest version: 1.2.0-alpha.24, downgrade is disallowed).
  backend:tor Apr 08 10:26:13.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
  backend:tor  +1s
  backend:tor Apr 08 10:26:13.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
  backend:tor  +118ms
  backend:tor Apr 08 10:26:14.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
  backend:tor  +237ms
  backend:tor Apr 08 10:26:14.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
  backend:tor Apr 08 10:26:14.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
  backend:tor  +297ms
  backend:tor Apr 08 10:26:14.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
  backend:tor Apr 08 10:26:14.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
  backend:tor  +220ms
  backend:tor Apr 08 10:26:15.000 [notice] Bootstrapped 100% (done): Done
  backend:tor  +915ms
  backend:conn launchCommunityFromStorage +4s
  backend:socket Launching community DEC2840BD9A3F6D80555F8D2F81A792C for QmQQzPfpfRjXsNtw48QjBdLJJ5w6uQxHBVnMY9gwkpuBnW +4s
  backend:conn Spawning hidden service for community DEC2840BD9A3F6D80555F8D2F81A792C, peer: QmQQzPfpfRjXsNtw48QjBdLJJ5w6uQxHBVnMY9gwkpuBnW +11ms
  backend:registration Initializing registration service for peer QmQQzPfpfRjXsNtw48QjBdLJJ5w6uQxHBVnMY9gwkpuBnW... +0ms
  backend:registration Certificate registration service listening on port: 37729 +1ms
Error: TOR: Connection already established
    at /tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:248582:24
    at new Promise (<anonymous>)
    at TorControl.connect (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:248580:22)
    at TorControl._sendCommand (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:248618:20)
    at /tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:248640:18
    at new Promise (<anonymous>)
    at TorControl.sendCommand (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:248638:22)
    at Tor.spawnHiddenService (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:248862:46)
    at CertificateRegistration.<anonymous> (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:242887:32)
    at CertificateRegistration.emit (node:events:513:28)
/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:243140
            throw new Error();
            ^

Error
    at process.<anonymous> (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:243140:19)
    at process.emit (node:events:513:28)
    at process.processEmit [as emit] (/tmp/.mount_Quiet-I2kkug/resources/app.asar/node_modules/backend-bundle/bundle.cjs:239587:34)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.12.1
```

**Comment by vinkabuki** [comment]
This is just attempt to initialize same community twice

**Comment by Kacper-RF** [comment]
PR: https://github.com/TryQuiet/quiet/pull/1450
