### ISSUE TITLE
Backend not closed properly, crash on reopen 

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1462]
System: MacOS on M1 (other systems and MacOS with intel are working)
Version: update from 1.1.0 to 1.2.0

What happen:
I had working account on version 1.1.0 and updated to 1.2.0. That caused Quiet to throw an error and stop working. I didn't saw this error on any update in our test alphas (tested on M1). Restarting and closing all Quiet related activities in activity monitor doesn't help.

**Logs:**

  quiet Initializing debug logger +0ms
WARNING: Missing strong random number source
  quiet Initializing debug logger +0ms
Error returned: <dictionary: 0x7ff846e39750> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x7ff846e398e8> { length = 18, contents = "Connection invalid" }
}
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
options {
  socketIOPort: '57429',
  appDataPath: '/Users/olgadegtiarova/Library/Application Support/Quiet',
  resourcesPath: '/Applications/Quiet.app/Contents/Resources',
  platform: 'desktop'
}
  backend:conn Creating https proxy agent: 57433 +0ms
  backend:socket Data server running on port 57429 +0ms
Checking for update
  backend:tor Initializing tor... +0ms
  backend:tor /Users/olgadegtiarova/Library/Application Support/Quiet/Quiet/torPid.json exists. Old tor pid: 21039 +51ms
  backend:tor Trying to spawn tor for the 0 time... +1ms
  backend:tor Found tor process with pid 21039. Killing... +93ms
  backend:tor Killing old tor, pid: 21039 +11ms
  backend:tor Apr 19 10:04:22.092 [notice] Tor 0.4.7.13 (git-7c1601fb6edd780f) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1s, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
  backend:tor Apr 19 10:04:22.092 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
  backend:tor  +19ms
  backend:tor Apr 19 10:04:22.092 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
  backend:tor Apr 19 10:04:22.093 [notice] Opening Socks listener on 127.0.0.1:57441
  backend:tor Apr 19 10:04:22.093 [notice] Opened Socks listener connection (ready) on 127.0.0.1:57441
  backend:tor Apr 19 10:04:22.093 [notice] Opening HTTP tunnel listener on 127.0.0.1:57433
  backend:tor Apr 19 10:04:22.093 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:57433
  backend:tor Apr 19 10:04:22.093 [notice] Opening Control listener on 127.0.0.1:57440
  backend:tor Apr 19 10:04:22.093 [notice] Opened Control listener connection (ready) on 127.0.0.1:57440
  backend:tor  +2ms
  backend:tor Apr 19 10:04:22.000 [notice] Bootstrapped 0% (starting): Starting
  backend:tor  +9ms
Update for version 1.2.0 is not available (latest version: 1.2.0, downgrade is disallowed).
  backend:tor Apr 19 10:04:22.000 [notice] Starting with guard context "default"
  backend:tor  +415ms
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
  backend:tor  +1s
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
  backend:tor  +37ms
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
  backend:tor  +52ms
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
  backend:tor  +113ms
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
  backend:tor  +0ms
  backend:tor Apr 19 10:04:23.000 [notice] Bootstrapped 100% (done): Done
  backend:tor  +153ms
  backend:conn launchCommunityFromStorage +7s
  backend:levelDB:err Getting 'community' ModuleError: Database is not open
    at maybeError (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:48313:27)
    at ClassicLevel.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:47789:9)
    at LocalDB.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:255644:34)
    at ConnectionsManager.launchCommunityFromStorage (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247480:51)
    at Namespace.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247088:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'LEVEL_DATABASE_NOT_OPEN'
} +0ms
  backend:levelDB:err Getting 'registrar' ModuleError: Database is not open
    at maybeError (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:48313:27)
    at ClassicLevel.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:47789:9)
    at LocalDB.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:255644:34)
    at ConnectionsManager.launchCommunityFromStorage (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247491:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Namespace.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247088:17) {
  code: 'LEVEL_DATABASE_NOT_OPEN'
} +2ms
  backend:socket Launching community AB089AD8B0018CFA15F826783784A4CD for QmTs8qTeYy1o41TtiestSWUh2YNoW2SEzCrkqmZMdSeBJp +8s
  backend:conn dataServer - launchCommunity +683ms
  backend:levelDB:err Getting 'community' ModuleError: Database is not open
    at maybeError (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:48313:27)
    at ClassicLevel.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:47789:9)
    at LocalDB.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:255644:34)
    at ConnectionsManager.launchCommunity (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247580:55)
    at DataServer.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247241:28)
    at DataServer.emit (node:events:513:28)
    at Socket.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:255071:26)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:378608:22)
    at /Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:378251:39 {
  code: 'LEVEL_DATABASE_NOT_OPEN'
} +690ms
ModuleError: Database is not open
    at maybeError (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:48313:27)
    at ClassicLevel.put (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:47926:9)
    at LocalDB.put (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:255653:23)
    at ConnectionsManager.launchCommunity (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247582:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DataServer.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247241:17) {
  code: 'LEVEL_DATABASE_NOT_OPEN'
}
/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247462
            throw new Error();
            ^

Error
    at process.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247462:19)
    at process.emit (node:events:513:28)
    at process.processEmit [as emit] (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:243898:34)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.12.1

<img width="365" alt="Screenshot 2023-04-19 at 10 18 55" src="https://user-images.githubusercontent.com/68909168/233013462-9f2a8513-25d2-455c-93a6-a2d0bb39c0a0.png">

**Comment by holmesworcester** [comment]
let's have our e2e tests run on m1

**Comment by EmiM** [comment]
Turns out this is **not** the problem of M1. This is the problem of Quiet and hanging backend.

For some reason there is a small chance that backend will not be closed properly (I could not reproduce that neither by closing Quiet in multiple ways nor by ctrl+c, I still don't know why it happens). When that happens backend holds a lock to leveldb. If one opens Quiet, leveldb creates instance, does not throw any error while opening the db and only throws error while trying to access db (get/put). Not very helpful.
Devs can reproduce that easily by running backend.cjs manually and then opening Quiet (on any OS).

**Comment by holmesworcester** [comment]
Is this an upstream bug in orbitdb? How can we fix it?

**Comment by kingalg** [comment]
Version: 1.2.1-alpha.3
Didn't encounter it recently, so I'm closing the issue. To be re-opened in case it happens again.
