### ISSUE TITLE
Error appears when Windows is updated

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1519]
Versions - update between Quiet-1.2.1-alpha.2 and Quiet-1.2.1-alpha.3 (I'm not 100% sure if update is what triggered it but it happened when I've tried to update and now every time I open Quiet I got this error)
System: Windows (Linux and Mac updated without any issues)

What happened: when testing update from Quiet-1.2.1-alpha.2 to Quiet-1.2.1-alpha.3 I got java script error.

![Screenshot 2023-05-11 at 11 49 28](https://github.com/TryQuiet/quiet/assets/68909168/a8b06b33-da53-4521-9638-750fde5e02d1)

Loggs:

Read extra envs: { TEST_MODE: 'true' }
2023-05-11T09:29:43.176Z quiet Initializing debug logger
setAsDefaultProtocolClient true
electron main
2023-05-11T09:29:44.304Z quiet Initializing debug logger
2023-05-11T09:29:44.329Z quiet Initializing debug logger
2023-05-11T09:29:44.432Z quiet Initializing debug logger
2023-05-11T09:29:44.433Z quiet Initializing debug logger
2023-05-11T09:29:44.436Z quiet Initializing debug logger
2023-05-11T09:29:44.439Z quiet Initializing debug logger
2023-05-11T09:29:44.439Z quiet Initializing debug logger
2023-05-11T09:29:44.439Z quiet Initializing debug logger
2023-05-11T09:29:44.440Z quiet Initializing debug logger
2023-05-11T09:29:44.440Z quiet Initializing debug logger
2023-05-11T09:29:44.441Z quiet Initializing debug logger
2023-05-11T09:29:44.473Z quiet Initializing debug logger
2023-05-11T09:29:44.548Z quiet Initializing debug logger
2023-05-11T09:29:44.707Z quiet Initializing debug logger
2023-05-11T09:29:44.741Z quiet Initializing debug logger
2023-05-11T09:29:44.761Z quiet Initializing debug logger
2023-05-11T09:29:44.762Z quiet Initializing debug logger
2023-05-11T09:29:44.763Z quiet Initializing debug logger
WARNING: Missing strong random number source
2023-05-11T09:29:45.146Z quiet Initializing debug logger
2023-05-11T09:29:45.285Z quiet Initializing debug logger
2023-05-11T09:29:45.285Z quiet Initializing debug logger
2023-05-11T09:29:45.291Z quiet Initializing debug logger
2023-05-11T09:29:45.292Z quiet Initializing debug logger
2023-05-11T09:29:45.293Z quiet Initializing debug logger
options {
  socketIOPort: '50280',
  appDataPath: 'C:\\Users\\WinFish\\AppData\\Roaming\\Quiet',
  resourcesPath: 'C:\\Users\\WinFish\\AppData\\Local\\Programs\\quiet\\resources',
  platform: 'desktop'
}
2023-05-11T09:29:45.310Z backend:conn Creating https proxy agent: 50285
2023-05-11T09:29:45.317Z backend:socket Data server running on port 50280
2023-05-11T09:29:45.458Z backend:tor Initializing tor...
'C:\Users\WinFish\AppData\Local\Programs\quiet\resources\tor\tor.exe' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: C:\Users\WinFish\AppData\Local\Programs\quiet\resources\tor\tor.exe --quiet --hash-password f843a0ff9ddbebdd37bbd12b0489e669
'C:\Users\WinFish\AppData\Local\Programs\quiet\resources\tor\tor.exe' is not recognized as an internal or external command,
operable program or batch file.
    at checkExecSyncError (node:child_process:896:11)
    at Object.execSync (node:child_process:968:15)
    at Object.execSync (node:electron/js2c/asar_bundle:2:12711)
    at Tor.generateHashedPassword (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:236933:60)
    at C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:236791:22
    at new Promise (<anonymous>)
    at Tor.init (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:236787:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Namespace.<anonymous> (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:227193:21) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 27 43 3a 5c 55 73 65 72 73 5c 57 69 6e 46 69 73 68 5c 41 70 70 44 61 74 61 5c 4c 6f 63 61 6c 5c 50 72 6f 67 72 61 6d 73 5c 71 75 69 65 74 5c 72 65 73 ... 108 more bytes>
  ],
  pid: 10216,
  stdout: <Buffer >,
  stderr: <Buffer 27 43 3a 5c 55 73 65 72 73 5c 57 69 6e 46 69 73 68 5c 41 70 70 44 61 74 61 5c 4c 6f 63 61 6c 5c 50 72 6f 67 72 61 6d 73 5c 71 75 69 65 74 5c 72 65 73 ... 108 more bytes>
}
C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:227577
            throw new Error();
            ^
Error
    at process.<anonymous> (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:227577:19)
    at process.emit (node:events:513:28)
    at process.processEmit [as emit] (C:\Users\WinFish\AppData\Local\Programs\quiet\resources\app.asar\node_modules\backend-bundle\bundle.cjs:224006:34)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
Node.js v18.12.1

Under this path C:\Users\WinFish\AppData\Local\Programs\quiet\resources\ we can see:
![Screenshot 2023-05-11 at 11 51 23](https://github.com/TryQuiet/quiet/assets/68909168/914970bb-2410-4003-a937-633dc0a7702b)
![Screenshot 2023-05-11 at 11 51 43](https://github.com/TryQuiet/quiet/assets/68909168/270ea787-3930-4ceb-b06d-4362688a904a)

**Comment by vinkabuki** [comment]
as we can see on the shared screens - for some reason we miss tor binary - it was either not copied during building artifact, or windows deleted it.

**Comment by holmesworcester** [comment]
How did this make it to QA? Are we still lacking e2e tests on Windows? 

Or does this problem only appear in an upgrade?

**Comment by vinkabuki** [comment]
it is 100% unclear what happened, only in an upgrade and only once.

**Comment by holmesworcester** [comment]
If we can't reproduce this when upgrading from the old version to this version, let's move it to blocked / can't reproduce.

**Comment by holmesworcester** [comment]
Could we change this error message to be more informative?

**Comment by vinkabuki** [comment]
which one?

**Comment by holmesworcester** [comment]
@kingalg if this hasn't come up again, let's close and archive.

**Comment by EmiM** [comment]
@kingalg does it still occur?

**Comment by kingalg** [comment]
@EmiM @holmesworcester No, I haven't seen this one for months. I'm ok with closing it if you have no objections.
