### ISSUE TITLE
Java Script error, error from ipfs in the freshly created community

### ISSUE THREAD

**Issue by kingalg** [TryQuiet/quiet#1845]
Version: 2.0.0-alpha.12
System: MacOS

Fresh community with only Owner and another user trying to join. 
The same error shows in this community after app restart.

<img width="503" alt="Screenshot 2023-09-21 at 12 40 49" src="https://github.com/TryQuiet/quiet/assets/68909168/3829c70e-841d-4872-a5b1-9f7aa6d504ae">

Frontend logs:

<img width="543" alt="Screenshot 2023-09-21 at 12 40 24" src="https://github.com/TryQuiet/quiet/assets/68909168/45f7c29a-1ef7-4762-8a48-038a45db8e65">

Backend logs: 

Read extra envs: { TEST_MODE: 'true' }
  quiet Initializing debug logger +0ms
[30658:0921/122410.009857:ERROR:process_singleton_posix.cc(1225)] Failed to extract pid from path: /Users/rumbleefish/Library/Application Support/Quiet/Quiet/SingletonLock
setAsDefaultProtocolClient true
electron main
  desktop:main:main Event: app.activate +0ms
  desktop:main:main Event: app.ready +4ms
  desktop:main:main Event: app.browser-window-created  +39ms
  desktop:main:main Event: app.browser-window-created  +12ms
  desktop:main:main Created mainWindow +12ms
  desktop:main:main Forked backend, PID: 30677 +102ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
WARNING: Missing strong random number source
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
options {
  socketIOPort: '50523',
  appDataPath: '/Users/rumbleefish/Library/Application Support/Quiet',
  resourcesPath: '/Applications/Quiet.app/Contents/Resources',
  platform: 'desktop'
}
configOptions {
  socketIOPort: '50523',
  torBinaryPath: '/Applications/Quiet.app/Contents/Resources/tor/x64/tor',
  torResourcesPath: '/Applications/Quiet.app/Contents/Resources/tor/x64',
  torControlPort: 50526,
  options: {
    env: {
      appDataPath: '/Users/rumbleefish/Library/Application Support/Quiet/Quiet'
    }
  },
  env: {},
  bootstrapMultiaddrs: [],
  createPaths: true
}
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
QUIRT DIR /Users/rumbleefish/Library/Application Support/Quiet/Quiet
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  backend:SocketService init:started +0ms
  backend:SocketService Data server running on port 50523 +1ms
  desktop:main:main Event: mainWindow did-finish-load +2s
Checking for update
Update for version 2.0.0-alpha.12 is not available (latest version: 2.0.0-alpha.12, downgrade is disallowed).
  backend:SocketService socket connection +1s
  backend:SocketService init: connection +0ms
  backend:SocketService init:finished +0ms
  backend:Tor Initializing tor... +0ms
  backend:Tor /Users/rumbleefish/Library/Application Support/Quiet/Quiet/torPid.json exists. Old tor pid: 30253 +1ms
  backend:Tor Found tor process with pid 30253. Killing... +94ms
[
  '--SocksPort',
  '50533',
  '--HTTPTunnelPort',
  '50527',
  '--ControlPort',
  '50526',
  '--PidFile',
  '/Users/rumbleefish/Library/Application Support/Quiet/Quiet/torPid.json',
  '--DataDirectory',
  '/Users/rumbleefish/Library/Application Support/Quiet/Quiet/TorDataDirectory',
  '--HashedControlPassword',
  '16:3B92D687D303894560B816812530236A606E2EE090A10CE09CB63BD3D5'
]
  backend:Tor Killing old tor, pid: 30253 +7ms
  backend:Tor Sep 21 12:24:15.860 [notice] Tor 0.4.7.13 (git-7c1601fb6edd780f) running on Darwin with Libevent 2.1.11-stable, OpenSSL 1.1.1s, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Unknown N/A as libc.
  backend:Tor Sep 21 12:24:15.860 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
  backend:Tor  +4ms
  backend:Tor Sep 21 12:24:15.860 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
  backend:Tor  +1ms
  backend:Tor Sep 21 12:24:15.862 [notice] Opening Socks listener on 127.0.0.1:50533
  backend:Tor  +1ms
  backend:Tor Sep 21 12:24:15.862 [notice] Opened Socks listener connection (ready) on 127.0.0.1:50533
  backend:Tor Sep 21 12:24:15.863 [notice] Opening HTTP tunnel listener on 127.0.0.1:50527
  backend:Tor Sep 21 12:24:15.863 [notice] Opened HTTP tunnel listener connection (ready) on 127.0.0.1:50527
  backend:Tor Sep 21 12:24:15.863 [notice] Opening Control listener on 127.0.0.1:50526
  backend:Tor  +1ms
  backend:Tor Sep 21 12:24:15.863 [notice] Opened Control listener connection (ready) on 127.0.0.1:50526
  backend:Tor  +0ms
  backend:Tor Sep 21 12:24:15.000 [notice] Bootstrapped 0% (starting): Starting
  backend:Tor  +14ms
init
  backend:ConnectionsManagerService attachTorEventsListeners +0ms
launch 1
  backend:ConnectionsManagerService launchCommunityFromStorage +1ms
launchCommunityFromStorage - community {
  id: '48ADF5FF2E41323BB88D6323B0310FC7',
  peerId: {
    id: 'QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff',
    privKey: 'CAASpgkwggSiAgEAAoIBAQC6XADEQm7BbwxFdnn4+a2C8F+bdkIzuEj+CHhLdNlzYk+m4zNDOAnDLRTupz7oUsv44C0qgqvuCQmrpWmUbprkQG6xORpBJHH/9EmjFPVGxgavLh5RX5tOw2jG4MPrc8F07Tm0lbeq8WEYL9ysOp69AmwyiwImVm6inBHogVtdu58re8Yhi92B8w8MCCs+JNHUZLhjb6PzGvk4BUjN/RyQ6kB104scDYTe3KXYz9v+7BarSckY6ZbY4yehp5gy40Y+9QMvLH8vHp0pD+7nbbW+TVBYrDn1wHjiRhVxQaZmeFEIhnlZEe8Yp11C2owG3VPKcxHP9sxho1/G4lJbPTEjAgMBAAECggEARLTay4C6mLI6UfnGKlbS861vcj99VNgigRXaU+d2rCWYvCyTn7qvTrf2Oa6LcNflv5HW1Q9sF8xZNmE7ta+5h2GB7fDhjxbCuNz1sRxu+XLU0A0uvE2FUtqUbI49bTc2Ice8OKniFzH63BH5R74s+/5Cqbe6SSwgie8EYzYd20ZINBEOa33xgkfJQx/JlhyEhspMt8lZ0H8z0ZoupcXmaZVbYUTDWFe3VwFusrGinLndrp+T3agF70o6vtDQoIiM7Aq9Td3YL4pHiq410/ViC1ZVb4VZz7ay80lFmH+xiOjIHHgrTK73VlNZEjQfEPouT4dX9lCckUTjAz0cS1bXYQKBgQD86sXLCZBCTcwNF3YN9GcKB6jlHWJKmkkx2mubjUtJ1RduG7cAVSt4RyeVr0kmGcZjDtMI3YN1MyV3/Oec9kWfmFl208LGs9/UdPtg6DBKXHkgNxfZEM5D6L/TNU5iFsM1hDznkCppYYXdeP+L1VdYE23Vtdp1LQGaGR1rEPdfOQKBgQC8oYmEuAeBLf5TvYHamm7Rk2e56G7D2duLTcVpMKBnHRblWmKs7IbkUsnKVr4m1egIlD/4A1Sh8NZvndi3ZHDsjSP1B95fZ2f817QtAdrMvnKZNySbU21LWhCqFxuc4WMsy3ZuiUnNfpESjqiIf76nVpZJqtsF1gtRbW8hTe03OwKBgHjOi3vYLZf+ISF/u1wfCbi4v+vwhSqtV5kAg7XhX7z8lBx8EIWQKRtioX3WJFKWrTRTuGnbpRcuPw95Ngi7ebYpx1IDBF51PMz2s7wuLCLY2OKSbkm4xU2at0XjiHVB+ixt5cmWCywa8R5A1Y+tb/MaFLSoEJk3zjQVGwAxMnfBAoGAJjzEqK+5bblKFeWTfiHSFw+/dhMk6PSvqXRxcRpXWa+u5X1GBXHJAl255BdjYnH4IE0VDox2SoGMpoGj3cExlvIheNlIfaRzkvCS6JC4rspoZqCj/gySWjT+rcwTX+Dcfscb0dpoqIxgkhdzGIB0wG0v9+z3ix5RmwcJAQJP9OMCgYB6LJdBdo0pxZM1O7ejsBAXRkpwy7WFg4+087M3UF83zdoBxuFGndTHSle6gZDXWbisMtNSjSPdwLWu1a+vCDInI1WuaArSxZCjYK0HH3jygnggR3iSJs/yDAKzN3sZAiFPpafkrmhRUsy+jfg+zlCFCKTKI0kHbpFV3xqdjQ1rzw==',
    pubKey: 'CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6XADEQm7BbwxFdnn4+a2C8F+bdkIzuEj+CHhLdNlzYk+m4zNDOAnDLRTupz7oUsv44C0qgqvuCQmrpWmUbprkQG6xORpBJHH/9EmjFPVGxgavLh5RX5tOw2jG4MPrc8F07Tm0lbeq8WEYL9ysOp69AmwyiwImVm6inBHogVtdu58re8Yhi92B8w8MCCs+JNHUZLhjb6PzGvk4BUjN/RyQ6kB104scDYTe3KXYz9v+7BarSckY6ZbY4yehp5gy40Y+9QMvLH8vHp0pD+7nbbW+TVBYrDn1wHjiRhVxQaZmeFEIhnlZEe8Yp11C2owG3VPKcxHP9sxho1/G4lJbPTEjAgMBAAE='
  },
  hiddenService: {
    onionAddress: 'x6okwfylard7n5ki2osdbb5zpejgsp26gnqjcmdkaqiytwxsw4moicyd.onion',
    privateKey: 'ED25519-V3:2N6C3rzs0jKCZvYsR/sNPrdRW6xCSYT6vrHhGPjSplHhJNLKCg2LfkOBhyDauZKdBXOtKgOPrgZlceRoYK/bAw=='
  },
  certs: {
    certificate: 'MIIDfDCCAyKgAwIBAgIGAYq3PEqeMAoGCCqGSM49BAMCMBUxEzARBgNVBAMTCm1hY2NvbjIxMDkwHhcNMjMwOTIxMTAxNDU2WhcNMzAwMTMxMjMwMDAwWjBJMUcwRQYDVQQDEz54Nm9rd2Z5bGFyZDduNWtpMm9zZGJiNXpwZWpnc3AyNmducWpjbWRrYXFpeXR3eHN3NG1vaWN5ZC5vbmlvbjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEm4dKJv1WrbILI01D1D4MQisrios3NsR8hySn0Yk2yTYAJ/IJLtjkD96sLEJizkJZcCMA8q59deSn96x/Qbik2jggIoMIICJDAJBgNVHRMEAjAAMAsGA1UdDwQEAwIAgDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwggFGBgkqhkiG9w0BCQwEggE3BIIBM82Ysn37ZYj2VMbIa3GURBS+TRPjDpdVRjHI4p7xpqs5ATd3jK/T/YyZQXidMYKa3Wup0TKiSYRwzsIcwPXED65YZ/pTjaEoRjcl6gJB7rgAi6sSL1bzlB5dDyS5oZgRiOw+nKhowg3XtpBPmMyJBgB65E0NIU/TS0Vm5q9ILTaHB5540kAisNJuC7rvQrjGibNK6NiRQiY30ktgD5RbUxgDbsxpP2Jqrg2qrZbrPkkKcee22MMSJRZm0VVXg0Eh5KIt1BF4gxjtZuR7QMpoW3Sa8tU6/LEGPouZTbWTnHc54BlkeR06XsLuDlfXZ9oGjWsEJr/mUOUT3CIOH9linYOB+tofE/J7EIsx+Tu0tptoTXhsWHGpuBzjH9hfp68Wi9qjO1nOWS5nLfmdex8v/d7VdkIwFwYKKwYBBAGDjBsCAQQJEwdtYWMyMTA5MD0GCSsGAQIBDwMBAQQwEy5RbVJrRGM0eHhXOHRzQmpVSFJjeENFQ0VmbXFUSnhXajdRYXQzeHVjM21IVGZmMEkGA1UdEQRCMECCPng2b2t3ZnlsYXJkN241a2kyb3NkYmI1enBlamdzcDI2Z25xamNtZGthcWl5dHd4c3c0bW9pY3lkLm9uaW9uMAoGCCqGSM49BAMCA0gAMEUCIGtCfmKDdLQMaC0QOOpdrO6UyXe5uI9p60aPwMtMxvvMAiEA9O4lOtWmc0DCE4wWwD5bfQVxPY5CRahAj62rs0lyNbk=',
    key: 'MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmpGbR/E1GYF0pGXOYH/2KI2wdY2UyD1p1xwTQUH79q6gCgYIKoZIzj0DAQehRANCAARJuHSib9Vq2yCyNNQ9Q+DEIrK4qLNzbEfIckp9GJNsk2ACfyCS7Y5A/erCxCYs5CWXAjAPKufXXkp/esf0G4pN',
    CA: [
      'MIIBVjCB/qADAgECAgEBMAoGCCqGSM49BAMCMBUxEzARBgNVBAMTCm1hY2NvbjIxMDkwHhcNMTAxMjI4MTAxMDEwWhcNMzAxMjI4MTAxMDEwWjAVMRMwEQYDVQQDEwptYWNjb24yMTA5MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjxag8Qdka+GExXUX1BuIT9dLjMwrUHwrtyRCQGkwduf4Sw3JSkEeRvdCQiYJBgEz6j/VVtJjsSccB+9wy1HT76M/MD0wDwYDVR0TBAgwBgEB/wIBAzALBgNVHQ8EBAMCAIYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMAoGCCqGSM49BAMCA0cAMEQCIDja59sbNIfN1rh1pwmLaqRNsjUG9eQzseuXfGx1ss2cAiAIIPLINaoG9qlKeL5HZHMpoZQ20EMCWkf9d/HAyx5Awg=='
    ]
  }
}
ConnectionsManager.launchCommunity peers: [ 'QmX7tHb174X4LhHcUcVUvUiSoxD1j6APzcqEa1FSDrzwtH' ]
  backend:ConnectionsManagerService Spawning hidden service for community 48ADF5FF2E41323BB88D6323B0310FC7, peer: QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff +2ms
  backend:Tor Sep 21 12:24:16.000 [notice] Starting with guard context "default"
  backend:Tor  +643ms
  backend:Tor Sep 21 12:24:16.000 [notice] New control connection opened from 127.0.0.1.
  backend:Tor  +11ms
  backend:Tor Sep 21 12:24:16.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
  backend:Tor  +8ms
  backend:ConnectionsManagerService Launching community 48ADF5FF2E41323BB88D6323B0310FC7, peer: QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff +661ms
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
Launching community 48ADF5FF2E41323BB88D6323B0310FC7, payload peers: QmX7tHb174X4LhHcUcVUvUiSoxD1j6APzcqEa1FSDrzwtH
  backend:ConnectionsManagerService libp2p params {
  peerId: PeerId(QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff),
  listenAddresses: [
    '/dns4/x6okwfylard7n5ki2osdbb5zpejgsp26gnqjcmdkaqiytwxsw4moicyd.onion/tcp/80/ws'
  ],
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    maxTotalSockets: Infinity,
    sockets: {},
    freeSockets: {},
    requests: {},
    options: {},
    secureProxy: false,
    proxy: { port: 50527, host: '127.0.0.1' },
    [Symbol(kCapture)]: false
  },
  localAddress: '/dns4/x6okwfylard7n5ki2osdbb5zpejgsp26gnqjcmdkaqiytwxsw4moicyd.onion/tcp/80/ws/p2p/QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff',
  targetPort: 50536,
  peers: [ 'QmX7tHb174X4LhHcUcVUvUiSoxD1j6APzcqEa1FSDrzwtH' ]
} +13ms
  backend:Libp2pService Initializing libp2p for QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff, bootstrapping with 1 peers +0ms
  quiet Initializing debug logger +0ms
  backend:ProcessInChunks Processing 1 items +0ms
  backend:ProcessInChunks Processing QmX7tHb174X4LhHcUcVUvUiSoxD1j6APzcqEa1FSDrzwtH failed, message: multiaddr "QmX7tHb174X4LhHcUcVUvUiSoxD1j6APzcqEa1FSDrzwtH" must start with a "/" +0ms
  backend:Libp2pService Initialized libp2p for peer QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff +1ms
  backend:StorageService Initializing storage +0ms
creating paths in fn - utils
  backend:StorageService Initialized storage +14ms
  quiet Initializing debug logger +0ms
counter ipfs 1
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
createOrbitDb peer id  PeerId(QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff)
  quiet Initializing debug logger +0ms
  quiet Initializing debug logger +0ms
  backend:StorageService 1/5 +103ms
  backend:StorageService createDbForChannels init +0ms
  backend:StorageService ALL CHANNELS COUNT: 1 +34ms
  backend:StorageService ALL CHANNELS COUNT: [ 'general_be3b4736fa38943ed02f2af393788186' ] +0ms
creating channel
  backend:StorageService Creating channel general_be3b4736fa38943ed02f2af393788186 +2ms
  backend:StorageService STORAGE: Finished createDbForChannels +0ms
  backend:StorageService 2/5 +0ms
  backend:StorageService createDbForCertificates init +0ms
  backend:Tor Sep 21 12:24:16.000 [notice] Bootstrapped 10% (conn_done): Connected to a relay
  backend:Tor  +212ms
channel {
  id: 'general_be3b4736fa38943ed02f2af393788186',
  name: 'general',
  owner: 'mac2109',
  timestamp: 1695291296730,
  description: 'Welcome to #general'
}
  backend:StorageService Set general_be3b4736fa38943ed02f2af393788186 to local channels +36ms
  backend:StorageService Created channel general_be3b4736fa38943ed02f2af393788186 +2ms
  backend:StorageService IPFS not started. Not subscribing to /orbitdb/zdpuApbb1WLkm5ouBTJJDj6sficPxWK42MoZDAKZhqxjrTPep/channels.general_be3b4736fa38943ed02f2af393788186 +0ms
  backend:StorageService Subscribing to channel  general_be3b4736fa38943ed02f2af393788186 +0ms
  backend:StorageService Subscribed to channel general_be3b4736fa38943ed02f2af393788186 +1ms
  backend:StorageService Loaded certificates to memory +3ms
  backend:StorageService ALL Certificates COUNT: 1 +1ms
  backend:StorageService STORAGE: Finished createDbForCertificates +0ms
  backend:StorageService 3/5 +0ms
  backend:StorageService certificatesRequests db init +0ms
  backend:StorageService ALL Certificates COUNT: 1 +26ms
  backend:StorageService STORAGE: Finished creating certificatesRequests db +0ms
  backend:StorageService 4/5 +0ms
  backend:StorageService createDbForCommunityMetadata init +0ms
  backend:StorageService 5/5 +20ms
  backend:StorageService Initialized DBs +0ms
  backend:StorageService Starting IPFS +1ms
storage initialized
  backend:ConnectionsManagerService Launched community 48ADF5FF2E41323BB88D6323B0310FC7 +271ms
Hunting for heisenbug: Backend initialized community and sent event to state manager
preparing listener
  backend:libp2p:websockets prepareListener +0ms
  backend:StorageService IPFS started +295ms
  backend:StorageService Pubsub - subscribe to /orbitdb/zdpuAubkQfjh7bUVJFvuCuNpkXc9LYF4NuPX7VS12e4ciy851/public-channels +0ms
  backend:StorageService Pubsub - subscribe to /orbitdb/zdpuAtjfjLokx2PW6UGrDQoB8VmEyq2i2endX4KuuD8efo7Vj/certificates +1ms
  backend:StorageService Pubsub - subscribe to /orbitdb/zdpuAq8czmPVqfV7B5fchXdFY11jVPNNymTnCJtvPDR1dCV3h/csrs +0ms
  backend:StorageService Pubsub - subscribe to /orbitdb/zdpuAtLG6WrE13SaXWmg52e1odsV3c97BPDQRudzzXFNqDoQD/community-metadata +0ms
  backend:StorageService Pubsub - subscribe to /orbitdb/zdpuApbb1WLkm5ouBTJJDj6sficPxWK42MoZDAKZhqxjrTPep/channels.general_be3b4736fa38943ed02f2af393788186 +0ms
  backend:SocketService Launching registrar for community 48ADF5FF2E41323BB88D6323B0310FC7, user QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff +1s
  backend:ConnectionsManagerService socketService - launchRegistrar +297ms
Setting owner perms data
  backend:SocketService On saveUserCsr +1ms
On saveUserCsr
  backend:StorageService About to save csr... +2ms
  backend:StorageService About to update community metadata +7ms
  backend:Tor Sep 21 12:24:16.000 [notice] Bootstrapped 14% (handshake): Handshaking with a relay
  backend:Tor  +381ms
  backend:Tor Sep 21 12:24:17.000 [notice] Bootstrapped 15% (handshake_done): Handshake with a relay done
  backend:Tor Sep 21 12:24:17.000 [notice] Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
  backend:Tor Sep 21 12:24:17.000 [notice] Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
  backend:Tor Sep 21 12:24:17.000 [notice] Bootstrapped 95% (circuit_create): Establishing a Tor circuit
  backend:Tor  +440ms
  backend:Tor Sep 21 12:24:18.000 [notice] New control connection opened from 127.0.0.1.
  backend:Tor  +807ms
  backend:Tor Sep 21 12:24:18.000 [notice] Bootstrapped 100% (done): Done
  backend:Tor  +136ms
  backend:Tor Sep 21 12:24:20.000 [notice] New control connection opened from 127.0.0.1.
  backend:Tor  +2s
  backend:libp2p:websockets server connecting with /dns4/wc6nnbsusdszkpoztjpijq3m73gxrlesmcrmyyi7ihgkmz4zccdghzad.onion/tcp/80/ws/p2p/QmbishYPDAuhBMz6GC6ieq5VGarhLEmH92Rr4zaCAJLuaa +36s
  backend:libp2p:websockets new inbound connection /dns4/wc6nnbsusdszkpoztjpijq3m73gxrlesmcrmyyi7ihgkmz4zccdghzad.onion/tcp/80/ws/p2p/QmbishYPDAuhBMz6GC6ieq5VGarhLEmH92Rr4zaCAJLuaa +2ms
  backend:libp2p:websockets inbound connection /dns4/wc6nnbsusdszkpoztjpijq3m73gxrlesmcrmyyi7ihgkmz4zccdghzad.onion/tcp/80/ws/p2p/QmbishYPDAuhBMz6GC6ieq5VGarhLEmH92Rr4zaCAJLuaa upgraded +4s
  backend:Libp2pService QmRkDc4xxW8tsBjUHRcxCECEfmqTJxWj7Qat3xuc3mHTff connected to QmbishYPDAuhBMz6GC6ieq5VGarhLEmH92Rr4zaCAJLuaa +40s
  backend:ProcessInChunks Stopping initial dial +40s
  backend:Libp2pService 1 connected peers +16ms
2023-09-21T10:25:01.175Z [ERROR] exchange-heads: Error: Not Found
    at Module.notFoundError (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:435861:16)
    at MemoryDatastore.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:435929:64)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async PersistentStore.load (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:454694:21)
    at async PersistentPeerStore.get (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:455025:20)
    at async findPeer (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:278656:14)
    at async id (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:278618:18)
    at async get_peer_id (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:483867:20) {
  code: 'ERR_NOT_FOUND'
}
TypeError: Cannot read properties of undefined (reading 'connect')
    at exchange_heads (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:484008:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async OrbitDB._onPeerConnected (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:484469:5)
/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:251779
            throw new Error();
            ^

Error
    at process.<anonymous> (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:251779:19)
    at process.emit (node:events:513:28)
    at process.processEmit [as emit] (/Applications/Quiet.app/Contents/Resources/app.asar/node_modules/backend-bundle/bundle.cjs:247059:34)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.12.1

**Comment by holmesworcester** [comment]
We should fix #179 and get logs if we are stuck on this.

**Comment by holmesworcester** [comment]
@kingalg how often do you see this error?

**Comment by kingalg** [comment]
@holmesworcester I've not seen it in a few last Quiet-alpha version.
