### ISSUE TITLE
Run tor tests on CI on windows and macos

### ISSUE THREAD

**Issue by EmiM** [TryQuiet/quiet#310]
When we run tor tests on windows and macos we encounter some timeout, tmp dir, other issues that are probably just connected to test environment.

```
● Tor manager (using tor) › should find hanging tor process and kill it
@quiet/waggle:     ENOTEMPTY: directory not empty, rmdir '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/quietTestTmp_-1764-HbbbeRO1KmD8/.quiet/TorDataDirectory'
@quiet/waggle: 
@quiet/waggle:       at rmkidsSync (node_modules/rimraf/rimraf.js:349:27)
@quiet/waggle:       at rmdirSync (node_modules/rimraf/rimraf.js:329:7)
@quiet/waggle:       at rimrafSync (node_modules/rimraf/rimraf.js:301:9)
@quiet/waggle:       at node_modules/rimraf/rimraf.js:336:39
@quiet/waggle:           at Array.forEach (<anonymous>)
@quiet/waggle:       at rmkidsSync (node_modules/rimraf/rimraf.js:336:26)
@quiet/waggle:       at rmdirSync (node_modules/rimraf/rimraf.js:329:7)
@quiet/waggle:       at rimrafSync (node_modules/rimraf/rimraf.js:301:9)
@quiet/waggle:       at node_modules/rimraf/rimraf.js:336:39
```

```
 FAIL  src/registration/registrationService.tor.test.ts (119.687 s)
@quiet/waggle:   Registration service (using tor)
@quiet/waggle:     × generates and saves certificate for a new user (115842 ms)
@quiet/waggle:   ● Registration service (using tor) › generates and saves certificate for a new user
@quiet/waggle:     FetchError: request to http://4avghtoehep5ebjngfqk5b43jolkiyyedfcvvq4ouzdnughodzoglzad.onion/register failed, reason: A "socket" was not created for HTTP request before 100000ms
```

**Comment by holmesworcester** [comment]
@EmiM @Kacper-RF is this still an issue?

**Comment by EmiM** [comment]
No
